apiVersion: v1
kind: Pod
metadata:
  name: liveness-demo
  namespace: monitoramento
  labels:
    test: liveness
spec:
  containers:
  - name: basic-container
    image: registry.k8s.io/busybox
    resources: {}
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 20; rm -f /tmp/healthy; sleep 100
    
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 10    