apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./Ingress/prometheus-ingress.yaml
  - ./Service/prometheus-svc.yaml
  - ./Service/grafana-svc.yaml 
  - ./Secrets/prometheus-secret.yaml
  - ./ConfigMap/prometheus-cm.yaml
  - ./Deployment/prometheus-deployment.yaml
  - ./Deployment/grafana.yaml
  - ./Deployment/simple-api.yaml  
  - ./Pod/liveness-demo.yaml
  - ./Pod/readiness-demo.yaml