apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    test: liveness
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        resources: {}
        ports:
        - containerPort: 3000

        args:
          - /bin/sh
          - -c
          - touch /tmp/healthy; sleep 20; rm -f /tmp/healthy; sleep 1000

        livenessProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 10