apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    test: liveness
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        resources: {}
        ports:
        - containerPort: 3000