apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
#      topologySpreadConstraints:
#        - maxSkew: 1
#          topologyKey: kubernetes,io/hostname
#          whenUnsatisfiable: ScheduleAnyway
#          labelSelector:
#            matchLabels:
#              app: simple-api

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: ssd-enabled
                    operator: In
                    values:
                      - "true"           
#          preferredDuringSchedulingIgnoredDuringExecution:
#            - preference:
#                matchExpressions:
#                  - key: ssd-enabled
#                    operator: In
#                    values:
#                      - "true"
#              weight: 1

         
      containers:
      - name: simple-api
        image: gustavoleitao/simple-api:1.0.3
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"          
          limits:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

        readinessProbe:
          httpGet:
            path: /
            port: 3000
        
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 18
          periodSeconds: 10