apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 10
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
      - name: simple-api
        image: gustavoleitao/simple-api:1.0.3
        resources:
          requests:
            memory: "32Gi"
            cpu: "900m"          
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

        readinessProbe:
          httpGet:
            path: /
            port: 3000
        
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 18
          periodSeconds: 10