apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress

spec:
  ingressClassName: nginx

  rules:
    - host: prometheus.localhost
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: prometheus-svc
                port:
                  number: 7700
    - host: grafana.localhost
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: grafana-svc
                port:
                  number: 3000
    - host: simple-api.localhost
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: simple-api-svc
                port:
                  number: 7777
  
  tls:
    - hosts:
        - prometheus.apps.lab
      secretName: prometheus-secret